//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisMatik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masalar
    {
        public long MasaID { get; set; }
        public string MasaNo { get; set; }
        public string MasaSiparisi { get; set; }
    }
}
